<a href="https://colab.research.google.com/github/kenzoyanome/ep_analysis/blob/main/everpeak_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#IMPORTANTE LIBRERÍAS RELEVANTES
import numpy             as np
import pandas            as pd
import matplotlib.pyplot as plt
import seaborn           as sns

#OTRAS CONFIGURACIONES: EN GENERAL, EN BLOQUE DE IMPORTS, SUELE EXISTIR UN ESPACIO DONDE SE HACEN DEFINICIONES GENERALES
#                       COMO ELIMINAR CIERTOS "WARNINGS" MOLESTOS, QUITAR LÍMITES DE PANDAS SOBRE CUANTAS FILAS O COLUMNAS
#                       MUESTRA AL MOMENTO DE IMPIRMIR EL DATAFRAME, DEFINIR ESTILOS PRE-DEFINIDOS PARA GRÁFICOS, ETC.

import warnings                                                  #MANEJO DE WARNINGS - ADVERTENCIAS
warnings.simplefilter(action='ignore', category = FutureWarning) #QUITAR WARNINGS MOLESTOS
pd.set_option('display.max_columns', None)                       #ELIMINA LIMITES DE PANDAS PARA MOSTRAR COLUMNAS
pd.set_option('display.max_rows', None)                          #ELIMINA LIMITES DE PANDAS PARA MOSTRAR FILAS
pd.set_option('display.max_colwidth', None)                      #AUTOAJUSTA ANCHO DE COLUMNAS
pd.set_option('display.float_format', lambda x: '%.3f' % x)      #PERMITE EVADIR EL MOSTRAR NÚMEROS CON NOTACIÓN CINETÍFICA
plt.rcParams['figure.dpi'] = 140                                 #NIVEL DE RESOLUCIÓN.

#RUTAS TABLAS: UBICACIONES DE LAS TABLAS EN REPOSITORIO DE GITHUB
df_path = "https://raw.githubusercontent.com/kenzoyanome/ep_analysis/refs/heads/main/everpeak_retail.csv"

In [5]:
#Cargar el DataSet y revisar estructura general
df = pd.read_csv(df_path)

display(df.head())
df.info()

,order_id,order_date,customer_id,product_category,price,quantity,order_value,payment_method,city,state,customer_age
0,1,2024-02-02,2616,Sports,269,50,13385,credit_card,New York,NY,66.000
1,2,2024-10-10,1736,Grocery,66,0,660,debit_card,Los Angeles,CA,24.000
2,3,2024-08-27,2543,Sports,267,0,5073,credit_card,Chicago,IL,23.000
3,4,2024-06-09,2252,Toys,114,125,14290,credit_card,New York,NY,70.000
4,5,2024-06-07,1583,Fashion,729,16,11754,credit_card,Houston,TX,75.000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5008 entries, 0 to 5007
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5008 non-null   int64
 1   order_date        5000 non-null   object
 2   customer_id       5008 non-null   int64
 3   product_category  5008 non-null   object
 4   price             5008 non-null   int64
 5   quantity          5008 non-null   int64
 6   order_value       5008 non-null   int64
 7   payment_method    5008 non-null   object
 8   city              4908 non-null   object
 9   state             4908 non-null   object
 10  customer_age      4858 non-null   float64
dtypes: float64(1), int64(5), object(5)
memory usage: 430.5+ KB

In [33]:
#Detectar valores faltantes (missing) y diversidad de valores en columnas
print(df.isna().sum())
#print(df.isna().mean()*100)
df.nunique()

order_id              0
order_date            8
customer_id           0
product_category      0
price                 0
quantity              0
order_value           0
payment_method        0
city                100
state               100
customer_age        150
dtype: int64

order_id            5008
order_date           381
customer_id         1829
product_category       8
price               1677
quantity             249
order_value         3889
payment_method         4
city                  10
state                  9
customer_age          64
dtype: int64